### ISSUE TITLE
custom repo useless ?

### ISSUE THREAD

**Issue by krionux** [FloeDesignTechnologies/ansible-haproxy#16]
Hello,

I'm wondering why are you using a custom repo ppa:vbernat ?

Removing this entry, fully works on debian jessie, with haproxy 1.5.8

**Comment by jaytaylor** [comment]
@krionux Last time I checked, Ubuntu required that PPA to be added to get HAProxy 1.5.x series.  Otherwise you'd be stuck with 1.4.x on Ubuntu.

**Comment by PierrePaul** [comment]
Exactly, on ubuntu 14.04 the default installed version : 
HA-Proxy version 1.4.24 2013/06/17
