### ISSUE TITLE
Not on ansible galaxy

### ISSUE THREAD

**Issue by Lavoaster** [FloeDesignTechnologies/ansible-haproxy#17]
Hi There,

I see that you have a meta file for ansible galaxy but I don't seem to be able to find this package on there.

Is this intended?

**Comment by tracphil** [comment]
It is in Galaxy https://galaxy.ansible.com/list#/roles/912

**Comment by spk** [comment]
New link https://galaxy.ansible.com/info/haproxy/

**Comment by benwebber** [comment]
Thanks @spk. That's not intentional. Opened https://github.com/ansible/galaxy/issues/278.

**Comment by PierrePaul** [comment]
Let me know if I can do something to help change the info namespace.

**Comment by benwebber** [comment]
@spk The Ansible Galaxy team fixed the download. Thanks for letting us know.
