### ISSUE TITLE
idempotence not met?

### ISSUE THREAD

**Issue by riemers** [FloeDesignTechnologies/ansible-haproxy#23]
Forgive me if i see it wrong, but when i run this role again on the same machine it keeps on saying "changed" while its the same config. So in the end i have 13 changes on my host while nothing has changed. Is this because your "building" the config which doesn't have any means to guarantee idempotence?

**Comment by PierrePaul** [comment]
Exactly, it is sad heh? I guess for this reason alone it would be worth the shot to create an ansible module, but at least this role work and fit most cases.

**Comment by riemers** [comment]
True, its either this one or a ninja file to set it up. latest ansible does support some haproxy controls now though.
