### ISSUE TITLE
Versioned releases

### ISSUE THREAD

**Issue by AMeng** [FloeDesignTechnologies/ansible-haproxy#38]
Would it be possible to get a versioned release of this role? Its important for many users to be able to lock down the role to a specific version, instead of always pulling the master branch.

According to the [Galaxy Docs](https://galaxy.ansible.com/intro#role-galaxy), this should be as easy as just adding tags in GitHub.

> If you applied any tags to your repository, Galaxy will automatically display a “version” for each tag. This means users users can choose the version (tag) to download.
...
To import new tags, you can trigger a re-import from the “Your Roles” page anytime.

This allows users to lock in a specific release in their `requirements.yml` like so:
```yaml
- src: info.haproxy
  version: v0.1
```

**Comment by SydOps** [comment]
+1

**Comment by PierrePaul** [comment]
I tagged this release 1.0 : https://galaxy.ansible.com/FloeDesignTechnologies/haproxy/
Thanks everyone, sorry for the wait.
